Add http, bash, jp, jq, ps
blinkops/blink-core pull request #2
Opened 2021-06-16 17:09 UTC by itsofirblink

2021-06-17 09:59 UTC, rimar-blink requested changes

2021-06-17 09:59 UTC, rimar-blink commented on actions/http_delete.action.yaml
> +# Describes the action and it's parameters
Why this isn't just 1 http action with method parameter?

2021-06-17 09:59 UTC, rimar-blink commented on actions/http_get.action.yaml
> +# Describes the action and it's parameters
need to be able to add http headers

2021-06-17 09:59 UTC, rimar-blink commented on actions/http_post.action.yaml
> +    required: true
body can be empty - will it work with the required flag?

2021-06-17 09:59 UTC, rimar-blink commented on actions/jq.action.yaml
> +    required: false
it's not clear from the description what's the difference between jp and jq

2021-06-17 09:59 UTC, rimar-blink commented on actions/http_post.action.yaml
> +  contentType:
default value application/json?

2021-06-17 09:59 UTC, rimar-blink commented on actions/jq.action.yaml
> +    required: false
unquoted field, what's the default?

2021-06-17 09:59 UTC, rimar-blink commented on implementation/http.go
> +func executeCoreHTTPDeleteAction(_ *plugin.ActionContext, request *plugin.ExecuteActionRequest) ([]byte, error) {
all http methods should be handled by 1 or 2 functions, perhaps 1 for GET/HEAD and another one for all the rest that can have a body

2021-06-17 09:59 UTC, rimar-blink commented on implementation/http.go
> +		ProtoMajor:       response.ProtoMajor,
ProtoMajor and ProtoMinor seem unneeded, please remove

2021-06-17 09:59 UTC, rimar-blink commented on implementation/http.go
> +	postBody, err := json.Marshal(data)
why json.Marshal?

2021-06-17 09:59 UTC, rimar-blink commented on implementation/implementation.go
> +type FinalOutput struct {
What's so final about this output? :) Maybe call it CommandOutput?

2021-06-17 09:59 UTC, rimar-blink commented on implementation/ps.go
> +		failureResult := FinalOutput{Output: string(outputBytes), Error: execErr.Error()}
looks like the same code as in bash, jq, jp commands, can you refactor and extract a shared function?

2021-06-18 18:28 UTC, itsofirblink commented on actions/http_post.action.yaml
> +    required: true
Changed

2021-06-18 18:28 UTC, itsofirblink commented on actions/jq.action.yaml
> +    required: false
Changed

2021-06-18 18:29 UTC, itsofirblink commented on actions/http_post.action.yaml
> +  contentType:
Why?

2021-06-18 18:29 UTC, itsofirblink commented on implementation/http.go
> +		ProtoMajor:       response.ProtoMajor,
Done

2021-06-18 18:30 UTC, itsofirblink commented on implementation/http.go
> +	postBody, err := json.Marshal(data)
That's how you send data

2021-06-18 18:30 UTC, itsofirblink commented on implementation/implementation.go
> +type FinalOutput struct {
Changed

2021-06-18 18:31 UTC, itsofirblink commented on implementation/http.go
> +func executeCoreHTTPDeleteAction(_ *plugin.ActionContext, request *plugin.ExecuteActionRequest) ([]byte, error) {
why? it looks better like that

2021-06-18 18:32 UTC, itsofirblink commented on actions/http_delete.action.yaml
> +# Describes the action and it's parameters
Why not?

2021-06-18 18:32 UTC, itsofirblink commented on actions/http_get.action.yaml
> +# Describes the action and it's parameters
Will add to post method

2021-06-19 10:30 UTC, danielsblinkops requested changes

2021-06-19 10:30 UTC, danielsblinkops commented on implementation/http.go
> +		Timeout: time.Second * 60,
Looks like this should be configurable in tthe action

2021-06-19 10:30 UTC, danielsblinkops commented on implementation/ps.go
> +func executeCorePsAction(_ *plugin.ActionContext, request *plugin.ExecuteActionRequest) ([]byte, error) {
i really dont see a reason for this action to exit, ps inside a blink controlled docker container is not really interesting

2021-06-19 10:30 UTC, danielsblinkops commented on implementation/implementation.go
> +		"python":      executeCorePythonAction,
lets change the python action to return only the output if there is no error

2021-06-19 16:07 UTC, itsofirblink commented on implementation/json.go
> +	command := exec.Command("/bin/echo", providedJson, "|", "/bin/jq", query)
Done it in another way

2021-06-20 07:40 UTC, rimar-blink requested changes

2021-06-20 07:40 UTC, rimar-blink commented on actions/http_delete.action.yaml
> +# Describes the action and it's parameters
it should be 1 http action, both from user perspective and from the code implementing it.

2021-06-20 07:40 UTC, rimar-blink commented on actions/http_get.action.yaml
> +# Describes the action and it's parameters
you should add headers to all http calls, one more reason to make it 1 action.

2021-06-20 07:40 UTC, rimar-blink commented on actions/http_post.action.yaml
> +  contentType:
user convinience? we should ask liran about it.

2021-06-20 07:40 UTC, rimar-blink commented on implementation/http.go
> +	postBody, err := json.Marshal(data)
what if it's not json?

2021-06-20 07:40 UTC, rimar-blink commented on implementation/http.go
> +func executeCoreHTTPDeleteAction(_ *plugin.ActionContext, request *plugin.ExecuteActionRequest) ([]byte, error) {
not really

2021-06-20 07:40 UTC, rimar-blink commented on implementation/ps.go
> +func executeCorePsAction(_ *plugin.ActionContext, request *plugin.ExecuteActionRequest) ([]byte, error) {
+1

2021-06-20 18:37 UTC, danielsblinkops approved these changes

2021-06-21 07:09 UTC, merged