S1147: Add error code to responses
blinkops/blink-core pull request #37
Opened 2021-11-15 15:48 UTC by itsofirblink

2021-11-16 08:43 UTC, Idanraman requested changes

2021-11-16 08:43 UTC, Idanraman commented on common/common.go
>  func GetCommandFailureResponse(output []byte, err error) ([]byte, error) {
Lets remove this func

2021-11-16 08:43 UTC, Idanraman commented on implementation/implementation.go
> +	if err != nil && resultBytes == nil {
Why? if we get err + result ,we still want to return as errored

2021-11-16 08:45 UTC, itsofirblink commented on implementation/implementation.go
> +	if err != nil && resultBytes == nil {
This if for sending a response with an ErrorCode :D
There is a System Error which returns an err and nothing else
but if you get a result with an error its probably something that we want to show the user

2021-11-17 10:49 UTC, Idanraman approved these changes

2021-11-17 12:42 UTC, merged