s1227: sudo credentials
blinkops/blink-core pull request #40
Opened 2021-12-16 15:46 UTC by rimar-blink

2021-12-19 07:59 UTC, itsofirblink approved these changes

2021-12-19 07:59 UTC, itsofirblink commented on implementation/cli.go
> +	cmd := fmt.Sprintf("/opt/blink/kubectl config set-cluster cluster --server=%s", apiServerURL)
const `/opt/blink`?

2021-12-20 13:25 UTC, itsofirblink requested changes

2021-12-20 13:25 UTC, itsofirblink commented on implementation/cli.go
> +	}
that's a problem cause you may pass both `github` and `gitlab` and it will not work :(

2021-12-20 13:39 UTC, rimar-blink commented on implementation/cli.go
> +	}
you can't pass more than 1 credentials to a step

2021-12-20 13:55 UTC, itsofirblink requested changes

2021-12-20 13:55 UTC, itsofirblink commented on implementation/cli.go
> +	}
move to a function and call only if `m` is not empty.

2021-12-20 13:55 UTC, itsofirblink commented on implementation/cli.go
>  			return nil, err
don't return error here, it may be a failure cause of missing secrets, just continue to execute without credentials :)

2021-12-20 14:32 UTC, rimar-blink commented on implementation/cli.go
>  			return nil, err
ok

2021-12-20 14:33 UTC, rimar-blink commented on implementation/cli.go
> +	}
moving to a function, but i want it to run even if m is null, to set the region

2021-12-20 14:43 UTC, itsofirblink approved these changes

2021-12-20 14:43 UTC, merged