TSK-2887-same-pee-for-subflow
blinkops/blink-core pull request #80
Opened 2022-03-11 21:52 UTC by rimar-blink

2022-03-12 07:17 UTC, itsofirblink requested changes

2022-03-12 07:17 UTC, itsofirblink commented on implementation/implementation.go
> +	}
Extract to function, 
Change to 'topExecutionId, ok :='

2022-03-13 06:53 UTC, itsofirblink approved these changes

2022-03-13 06:56 UTC, merged

2022-03-13 10:29 UTC, havivrosh commented on implementation/implementation.go
> +func getTopExecutionId(ctx *plugin.ActionContext) (string, error) {
i think you can use command.Context.ParentPlaybook.TopExecutionId
in the past the system was using the func determineExecutionId for this